### ISSUE TITLE
TypeError: convert() got an unexpected keyword argument 'input_name'

### ISSUE THREAD

**Issue by engahmed1190** [prisma-ai/torch2coreml#1]
when running setup.sh an error appears 
```
Traceback (most recent call last):
  File "convert-fast-neural-style.py", line 54, in <module>
    main()
  File "convert-fast-neural-style.py", line 39, in main
    'blue_bias': 103.939
TypeError: convert() got an unexpected keyword argument 'input_name'
Traceback (most recent call last):
  File "convert-fast-neural-style.py", line 54, in <module>
    main()
  File "convert-fast-neural-style.py", line 39, in main
    'blue_bias': 103.939
TypeError: convert() got an unexpected keyword argument 'input_name'
Traceback (most recent call last):
  File "convert-fast-neural-style.py", line 54, in <module>
    main()
  File "convert-fast-neural-style.py", line 39, in main
    'blue_bias': 103.939
TypeError: convert() got an unexpected keyword argument 'input_name'
Traceback (most recent call last):
  File "convert-fast-neural-style.py", line 54, in <module>
    main()
  File "convert-fast-neural-style.py", line 39, in main
    'blue_bias': 103.939
TypeError: convert() got an unexpected keyword argument 'input_name'
```

environment contains 

> adium-theme-ubuntu (0.3.4)
> coremltools (0.6.3)
> decorator (4.0.6)
> h5py (2.7.0)
> ipython (2.4.1)
> numpy (1.13.1)
> pexpect (4.0.1)
> pip (9.0.1)
> protobuf (3.4.0)
> ptyprocess (0.5)
> pycurl (7.43.0)
> python-apt (1.1.0b1)
> PyYAML (3.12)
> setuptools (36.3.0)
> simplegeneric (0.8.1)
> six (1.10.0)
> torch (0.2.0.post3)
> torch2coreml (0.1.0)
> unity-lens-photos (1.0)
> virtualenv (15.1.0)
> wheel (0.29.0)

**Comment by opedge** [comment]
Please update torch2coreml to the latest version 0.1.0 and re-checkout repo with example. The API changed to support multiple inputs and outputs.

**Comment by engahmed1190** [comment]
@opedge `Requirement already up-to-date: torch2coreml in /usr/local/lib/python2.7/dist-packages`
the problem mainly in this part 
 ```
coreml_model = convert(
        args.input,
        input_shape,
        input_name='inputImage',
        output_name='outputImage',
        is_image_input=True,
        preprocessing_args={
            'is_bgr': True,
            'red_bias': -123.68,
            'green_bias': -116.779,
            'blue_bias': -103.939
        },
        is_image_output=True,
        deprocessing_args={
            'is_bgr': True,
            'red_bias': 123.68,
            'green_bias': 116.779,
            'blue_bias': 103.939
        }

```


there is a problem in the input_name 
`TypeError: convert() got an unexpected keyword argument 'input_name'`


try it by one model only 

> python convert-fast-neural-style.py -input prepared_models/composition_vii.t7 -output coreml_models/composition.mlmodel

same error

> Traceback (most recent call last):
>   File "convert-fast-neural-style.py", line 54, in <module>
>     main()
>   File "convert-fast-neural-style.py", line 39, in main
>     'blue_bias': 103.939
> TypeError: convert() got an unexpected keyword argument 'input_name'

**Comment by opedge** [comment]
@engahmed1190 Yes, I already updated example to support new API: https://github.com/prisma-ai/torch2coreml/blob/master/example/fast-neural-style/convert-fast-neural-style.py#L22-L41
Please update repo.

**Comment by engahmed1190** [comment]
Thanks , it works but  stopped due to 

> Out of memory: Kill process 29259 (python) score 621 or sacrifice child

is their any kind of solution for this issue

**Comment by opedge** [comment]
How much RAM is in your machine? May be you could try it on machine with more memory.

**Comment by engahmed1190** [comment]
6 Gb Ram and also I have a gpu .
I will try on another machine thanks

**Comment by engahmed1190** [comment]
Thanks , it works !
