### ISSUE TITLE
High Memory Usage in iOS

### ISSUE THREAD

**Issue by guanjhensu** [prisma-ai/torch2coreml#12]
I try the example iOS code provided by this repo. 

https://github.com/prisma-ai/torch2coreml/tree/master/example/fast-neural-style/ios

The coreml model is only ~10MB. However, the memory usage is very high, usually up to 200MB, which causes the app to terminated due to memory issue sometimes.

<img width="265" alt="2017-10-11 3 17 02" src="https://user-images.githubusercontent.com/13248757/31426940-02a32ece-ae98-11e7-89fa-444bc10f7629.png">

**Comment by opedge** [comment]
You can decrease input size, thus it need to find a balance between quality (input size) and performance/resource usage.

**Comment by guanjhensu** [comment]
Thanks for your comment. It works!
