### ISSUE TITLE
unable to import mlmodel to ios

### ISSUE THREAD

**Issue by theheena** [prisma-ai/torch2coreml#7]
when i try to import mlmodel, for example candy.mlmodel, to xcode, I got a validation error saying:

"There was a problem in decoding this coreml document"
validator error: In layer instancenormalization_5: incorrect mean size 0

**Comment by opedge** [comment]
@theheena What beta version of Xcode 9 and beta iOS 11 you use?

**Comment by theheena** [comment]
it was beta 3 for xcode but now after updating it, the model got successfully imported.

**Comment by mdramos** [comment]
the issue exists in version 9.0
